# Starter pipeline
- task: FortifyOnDemandStatic@5
  inputs:
    FortifyProjects: 
    BSIToken: 'eyJ0ZW5hbnRJZCI6MzQ2LCJ0ZW5hbnRDb2RlIjoidGFtX3RlYW1fdGVzdCIsInJlbGVhc2VJZCI6Mjg2MzQ3LCJwYXlsb2FkVHlwZSI6IkFOQUxZU0lTX1BBWUxPQUQiLCJhc3Nlc3NtZW50VHlwZUlkIjoyNzQsInRlY2hub2xvZ3lUeXBlIjoiLk5FVCIsInRlY2hub2xvZ3lUeXBlSWQiOjEsInRlY2hub2xvZ3lWZXJzaW9uIjoiNC44IiwidGVjaG5vbG9neVZlcnNpb25JZCI6MzAsImF1ZGl0UHJlZmVyZW5jZSI6IkF1dG9tYXRlZCIsImF1ZGl0UHJlZmVyZW5jZUlkIjoyLCJpbmNsdWRlVGhpcmRQYXJ0eSI6ZmFsc2UsImluY2x1ZGVPcGVuU291cmNlQW5hbHlzaXMiOmZhbHNlLCJwb3J0YWxVcmkiOiJodHRwczovL2Ftcy5mb3J0aWZ5LmNvbSIsImFwaVVyaSI6Imh0dHBzOi8vYXBpLmFtcy5mb3J0aWZ5LmNvbSIsInNjYW5QcmVmZXJlbmNlIjoiU3RhbmRhcmQiLCJzY2FuUHJlZmVyZW5jZUlkIjoxfQ=='
    APIAuthenticationType: '1'
    APIKey: '590e4a99-7546-4639-9fa3-3ffd31342a00'
    APISecret: 'NCY3e0dlTWlEVExac2IzdVpxNWhQXUlvanpHaTNY0'
    EntitlementPreference: '1'
    InProgressScanActionType: '0'
    RemediationScanPreference: '0'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
